version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  jobs:
    pre_build:
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "jupyter-book config sphinx docs/"
      - "python modify_conf.py"
      # Replace .venv-fesslix kernel with python3 for RTD
      - "find docs/ -name '*.ipynb' -exec sed -i 's/\".venv-fesslix\"/\"python3\"/g' {} +"
      
sphinx:
  configuration: docs/conf.py  # Path to Sphinx configuration file
  
python:
   install:
   - requirements: docs/requirements.txt
#   - method: pip
#     path: .

formats:
  - pdf
  - epub

